export const INCOMING_ACTIONS_TYPES = {
  AUTH_CODE: 'AUTH_CODE',
  SET_NAV_BAR: 'SET_NAV_BAR',
  SET_BACK_BTN: 'SET_BACK_BTN',
  MINIAPP_LOADED: 'MINIAPP_LOADED',
  OPEN_MINIAPP_BY_ID: 'OPEN_MINIAPP_BY_ID',
  GET_SYSTEM_INFO:'GET_SYSTEM_INFO',
  TRADE_PAY:'TRADE_PAY'
}

export const OUTGOING_ACTIONS_TYPES = {
  AUTH_CODE: 'AUTH_CODE',
  DEEP_LINK: 'DEEP_LINK',
  SET_BACK_BTN: 'SET_BACK_BTN',
  MINIAPP_LOADED: 'MINIAPP_LOADED',
  GET_SYSTEM_INFO: 'GET_SYSTEM_INFO',
  TRADE_PAY: 'TRADE_PAY',
}

export const AUTH_SCOPES = {
  AUTH_USER: 'auth_user',
}
